export const ADD_FRIDGE = 'ADD_FRIDGE';
export const LOAD_FRIDGES = 'LOAD_FRIDGES';
export const CONFIRM_FRIDGE = 'CONFIRM_FRIDGE';

export const FETCH_FRIDGE_START = 'FETCH_FRIDGE_START';
export const FETCH_FRUEDGE_FAIL = 'FETCH_FRIDGE_FAIL';